# version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai_kb
      - MONGO_DB=ai_kb
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    network_mode: "bridge"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: kylinja
      MONGO_INITDB_ROOT_PASSWORD: NoUzmongA7GDKN9L

  

volumes:
  mongo_data:
  qdrant_data:

# networks:
#   my_network:
#     external: true