# version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ../app/.env
    depends_on:
      - mongo
    network_mode: bridge

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

# networks:
#   my_network:
#     external: true